# Site settings
baseurl: ""
permalinks: none
repo: "https://github.com/amonks/pfordrawing"
title: "Processing Sketches"

links:
  - name: "Andrew Monks"
    url: "http://monks.co"
  - name: "paint sketch"
    url: "http://amonks.github.io/painter/"
  - name: "blank procesisng.js sketch"
    url: "blank.txt"
  - name: "license"
    url: "LICENSE.html"

# Build settings
markdown: kramdown
