# Site settings
baseurl: "/pfordrawing" # run `jekyll serve --baseurl "" locally
permalinks: none
repo: "https://github.com/amonks/pfordrawing"
title: "Programming For Drawing"

# Build settings
markdown: kramdown
