# Site settings
# baseurl: "/pfordrawing" # server
baseurl: "" # local
permalinks: none
repo: "https://github.com/amonks/pfordrawing"
title: "Programming For Drawing"

# Build settings
markdown: kramdown
